version: '2'

services:
  web:
    build: .
    image: pi_tv
    volumes:
      - .:/app
    expose: 
      - "80"  
    ports:
      - "80:80"
    env_file: .env
    restart: always
    command: uwsgi --http 0.0.0.0:80 --wsgi-file=wsgi.py --callable app --master --processes 2 --max-requests 100 --chdir app  --stats 0.0.0.0:8001